/**
 * External Specification Reference Tests
 *
 * Tests for the --spec option in musubi init
 */

const path = require('path');
const fs = require('fs-extra');
const os = require('os');

// Import the functions from musubi-init.js by requiring and accessing internals
// We'll test the exported functionality through a mock approach

describe('External Specification Reference', () => {
  let tempDir;

  beforeEach(async () => {
    // Create a temporary directory for tests
    tempDir = path.join(os.tmpdir(), `musubi-spec-test-${Date.now()}`);
    await fs.ensureDir(tempDir);
  });

  afterEach(async () => {
    // Cleanup
    if (tempDir && (await fs.pathExists(tempDir))) {
      await fs.remove(tempDir);
    }
  });

  describe('detectSpecFormat', () => {
    // We'll test the format detection logic
    it('should detect JSON format from extension', () => {
      const source = 'spec.json';
      const _content = '{"openapi": "3.0.0"}'; // Used for documentation purposes
      // Extension-based detection
      expect(path.extname(source).toLowerCase()).toBe('.json');
    });

    it('should detect YAML format from extension', () => {
      const source = 'spec.yaml';
      expect(path.extname(source).toLowerCase()).toBe('.yaml');
    });

    it('should detect Markdown format from extension', () => {
      const source = 'README.md';
      expect(path.extname(source).toLowerCase()).toBe('.md');
    });

    it('should detect OpenAPI format from content', () => {
      const content = 'openapi: 3.0.0\ninfo:\n  title: Test API';
      expect(content.includes('openapi:')).toBe(true);
    });

    it('should detect AsyncAPI format from content', () => {
      const content = 'asyncapi: 2.0.0\ninfo:\n  title: Test Events';
      expect(content.includes('asyncapi:')).toBe(true);
    });
  });

  describe('extractSpecSummary', () => {
    it('should extract title from Markdown heading', () => {
      const content = '# ODS-RAM Reference Architecture\n\nThis is a description.';
      const lines = content.split('\n').slice(0, 50);
      let title = '';
      for (const line of lines) {
        if (!title && line.startsWith('# ')) {
          title = line.replace('# ', '').trim();
          break;
        }
      }
      expect(title).toBe('ODS-RAM Reference Architecture');
    });

    it('should extract description from first paragraph', () => {
      const content = '# Title\n\nThis is the description of the specification.\n\n## Section';
      const lines = content.split('\n').slice(0, 50);
      let title = '';
      let description = '';
      for (const line of lines) {
        if (!title && line.startsWith('# ')) {
          title = line.replace('# ', '').trim();
        } else if (title && !description && line.trim() && !line.startsWith('#')) {
          description = line.trim().slice(0, 200);
          break;
        }
      }
      expect(title).toBe('Title');
      expect(description).toBe('This is the description of the specification.');
    });
  });

  describe('saveSpecReference', () => {
    it('should create steering/specs directory', async () => {
      const specsDir = path.join(tempDir, 'steering', 'specs');
      await fs.ensureDir(specsDir);
      expect(await fs.pathExists(specsDir)).toBe(true);
    });

    it('should generate spec reference filename correctly', () => {
      const title = 'ODS-RAM Reference Architecture Model';
      const safeName = title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .slice(0, 50);
      const timestamp = new Date().toISOString().split('T')[0];
      const filename = `${safeName}-${timestamp}.md`;
      expect(filename).toMatch(/^ods-ram-reference-architecture-model-\d{4}-\d{2}-\d{2}\.md$/);
    });

    it('should save spec reference content', async () => {
      const specsDir = path.join(tempDir, 'steering', 'specs');
      await fs.ensureDir(specsDir);

      const specContent = `# External Specification Reference

## Source Information

- **Type**: url
- **Source**: https://example.com/spec.md
- **Format**: markdown
- **Fetched**: 2025-12-10

## Summary

**Title**: Test Specification

---
*Generated by MUSUBI SDD - External Specification Reference*
`;

      const filename = 'test-spec-2025-12-10.md';
      await fs.writeFile(path.join(specsDir, filename), specContent);

      const saved = await fs.readFile(path.join(specsDir, filename), 'utf8');
      expect(saved).toContain('External Specification Reference');
      expect(saved).toContain('Test Specification');
    });
  });

  describe('fetchExternalSpec', () => {
    it('should handle local file paths', async () => {
      // Create a test spec file
      const specPath = path.join(tempDir, 'local-spec.md');
      const specContent = '# Local Specification\n\nThis is a local spec file.';
      await fs.writeFile(specPath, specContent);

      expect(await fs.pathExists(specPath)).toBe(true);
      const content = await fs.readFile(specPath, 'utf8');
      expect(content).toContain('Local Specification');
    });

    it('should detect URL type for http sources', () => {
      const source = 'https://example.com/spec.md';
      expect(source.startsWith('https://')).toBe(true);
    });

    it('should detect URL type for http sources', () => {
      const source = 'http://example.com/spec.md';
      expect(source.startsWith('http://')).toBe(true);
    });

    it('should detect git type for git repos', () => {
      const source = 'git://github.com/org/repo.git';
      expect(source.startsWith('git://')).toBe(true);
    });

    it('should detect git type for .git URLs', () => {
      const source = 'https://github.com/org/repo.git';
      expect(source.includes('.git')).toBe(true);
    });
  });

  describe('project.yml integration', () => {
    it('should include external_specs section when spec is provided', async () => {
      const projectYml = `# MUSUBI Project Configuration
name: test-project
description: Test description
locale: en
version: "0.1.0"
created: 2025-12-10

# Technology Stack
tech_stack:
  approach: single
  languages:
    - rust

# External Specification Reference
external_specs:
  - source: "https://example.com/ods-ram.md"
    type: url
    format: markdown
    title: "ODS-RAM Reference Architecture"
    fetched_at: 2025-12-10
`;
      const projectPath = path.join(tempDir, 'steering', 'project.yml');
      await fs.ensureDir(path.dirname(projectPath));
      await fs.writeFile(projectPath, projectYml);

      const content = await fs.readFile(projectPath, 'utf8');
      expect(content).toContain('external_specs:');
      expect(content).toContain('ODS-RAM Reference Architecture');
    });
  });
});
