name: musubi
description: A software project using MUSUBI SDD
locale: ja
version: 5.6.0
created: 2025-12-10T00:00:00.000Z
tech_stack:
  approach: undecided
  languages:
    - undecided
languages:
  - javascript
  - typescript
  - python
  - ruby
frameworks:
  - name: Express
    version: detected
    purpose: framework
  - name: Jest
    version: detected
    purpose: framework
  - name: ESLint
    version: detected
    purpose: framework
  - name: Prettier
    version: detected
    purpose: framework
