project_name: musubi-sdd
description: >-
  Ultimate Specification Driven Development Tool with 25 Agents for 7 AI Coding Platforms (Claude
  Code, GitHub Copilot, Cursor, Gemini CLI, Windsurf, Codex, Qwen Code)
version: 2.2.0
languages:
  - javascript
  - typescript
  - python
frameworks:
  - name: Jest
    version: detected
    purpose: framework
  - name: ESLint
    version: detected
    purpose: framework
  - name: Prettier
    version: detected
    purpose: framework
conventions:
  architecture_pattern: unknown
  directory_structure:
    src: src/
steering:
  auto_update:
    enabled: false
    frequency: on-demand
  excluded_paths:
    - node_modules/**
    - dist/**
    - build/**
    - .git/**
    - '*.log'
  memories:
    enabled: true
    path: steering/memories/
    max_file_size_kb: 500
    retention_days: 365
agents:
  default_language: ja
  bilingual_output:
    enabled: true
    languages:
      - en
      - ja
  output:
    gradual_generation: true
    progress_indicators: true
    large_file_splitting: true
    split_threshold_lines: 300
workflow:
  testing:
    required: true
    coverage_threshold: 80
  quality_gates:
    - name: lint
      command: npm run lint
      required: true
custom_rules:
  - All development shall follow specification-first approach
  - All code shall maintain high quality standards
  - Documentation shall be kept up to date
