# MUSUBI Project Configuration
name: musubi
description: Ultimate Specification Driven Development Tool with Review Gate Engine
locale: ja
version: "6.2.3"
created: 2025-12-12
updated: 2026-01-01

# Technology Stack
tech_stack:
  approach: undecided
  languages:
    - undecided  # To be determined
