# MUSUBI Project Configuration
name: musubi
description: Ultimate Specification Driven Development Tool with Review Gate Engine
locale: ja
version: "6.2.0"
created: 2025-12-12
updated: 2025-12-31

# Technology Stack
tech_stack:
  approach: undecided
  languages:
    - undecided  # To be determined
